ifeq ($(CI_FORCE_REBUILD),1)
NOCACHE=--no-cache
RECREATE=--force-recreate
else
NOCACHE=
RECREATE=
endif
ifeq ($(CI_VERBOSE),1)
BUILDKIT_PROGRESS=plain
endif

all:
	DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=$(BUILDKIT_PROGRESS) docker build $(NOCACHE) --file CI/Dockerfile.ci .
